#!/bin/sh

# @reboot /bin/bash -li ~/cron_scgi

if ! command -v tmux >/dev/null 2>&1
then
	screen -s "/bin/bash" -dmS "scgi_app"

	screen -S "scgi_app" -X stuff "cd ~/git_repo/GH_Weather_Station/rust\n"

	screen -S "scgi_app" -X stuff "cargo run --bin scgi_app\n"
else
	tmux new-session -d -c "${HOME}/git_repo/GH_Weather_Station/rust" "cargo run --bin scgi_app"
fi
