[package]
name = "bme688"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2cdev = { workspace = true }
weather_err = { path = "../weather_err" }
