[common]
sample_period_in_mins = 15
port = 8080

[indoor]
dev = "/dev/i2c-bme688"
database = "indoor.db"
db_table = "Indoor"
host = "gandalf.home.arpa"

[outdoor]
temp_dev = "/dev/i2c-sht31"
wind_dev = '/dev/ttyACM0'
database = "outdoor.db"
db_table = "Outdoor"
host = "eowyn.dyn.home.arpa"

[scgi]
sock_name = "/run/lighttpd/scgi_app"
sock_user = "lighttpd"
sock_group = "lighttpd"
database = "combined.db"
db_table = "Combined"

