[common]
sample_period_in_mins = 15
port = 8080

[indoor]
dev = "/dev/i2c-bme688"
database = "indoor.db"
db_table = "Indoor"

[outdoor]
wind_dev = '/dev/ttyACM0'
database = "outdoor.db"
db_table = "Outdoor"


