[package]
name = "weather_err"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["fs", "io-util", "rt", "rt-multi-thread", "time", "net"] }
i2cdev = { workspace = true }
sqlite = { workspace = true }
toml = { workspace = true }
