[package]
name = "outdoor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["fs", "io-util", "rt", "rt-multi-thread", "time"] }
chrono = "0.4.38"
approx = "0.5.1"

toml = { workspace = true }
sqlite = { workspace = true }

